#!/usr/bin/env bash
# render-index.sh — regenerate INDEX.md from all SKILL.md rule indexes.
#
# Walks modules/best-practices/skills/*/SKILL.md, extracts the rule index
# (bullet lines like "- **PREFIX-NNN** — summary"), and writes a flat
# cross-skill table to INDEX.md at the plugin root.
#
# Usage:
#   tools/render-index.sh
#
# Output is deterministic — safe to run repeatedly and commit the result.

set -euo pipefail

TOOLS_DIR="$(cd "$(dirname "$0")" && pwd)"
PLUGIN_ROOT="$(dirname "$TOOLS_DIR")"
SKILLS_ROOT="${PLUGIN_ROOT}/skills"
OUT="${PLUGIN_ROOT}/INDEX.md"

# strip_fences <file> — emit file contents with fenced code blocks
# elided. Example snippets inside ```…``` legitimately contain
# rule-shaped placeholders (PREFIX-NNN) that must not be rendered
# as real index entries.
strip_fences() {
  awk '
    /^```/ { in_block = !in_block; next }
    !in_block { print }
  ' "$1"
}

# Header.
{
  echo "# Best-practices library — rule index"
  echo
  echo "_Auto-generated by \`tools/render-index.sh\`. Do not edit by hand._"
  echo
  echo "Every rule across every skill, with links into the reference"
  echo "files. Skills are listed alphabetically by directory name."
  echo
} > "$OUT"

shopt -s nullglob
skills=()
for d in "$SKILLS_ROOT"/*/; do
  skills+=("$d")
done

# Sort skills by directory name for deterministic output.
IFS=$'\n' sorted=($(printf "%s\n" "${skills[@]}" | sort))
unset IFS

for skill_dir in "${sorted[@]}"; do
  skill_name="$(basename "$skill_dir")"
  skill_file="${skill_dir}SKILL.md"
  [[ -f "$skill_file" ]] || continue

  # Extract description from frontmatter.
  description="$(awk -F': ' '/^---$/{c++; next} c==1 && /^description: /{ sub(/^description: /, ""); print; exit }' "$skill_file")"

  {
    echo "## ${skill_name}"
    echo
    if [[ -n "$description" ]]; then
      echo "_${description}_"
      echo
    fi
  } >> "$OUT"

  # Extract bullet rules: lines like `- **PREFIX-NNN** — summary`.
  # Strip fenced code blocks first so example snippets in SKILL.md don't
  # leak placeholder rule IDs into the index.
  # Resolve the appropriate references/<topic>.md by deriving topic from
  # the prefix (lowercase). If the file doesn't exist, link to the skill
  # directory itself.
  rule_lines="$(strip_fences "$skill_file" | grep -E '^- \*\*[A-Z]{2,7}-[0-9]{3,}\*\* ' || true)"
  if [[ -z "$rule_lines" ]]; then
    echo "_(no rules listed in SKILL.md rule index yet)_" >> "$OUT"
    echo >> "$OUT"
    continue
  fi

  # Render as a table.
  {
    echo "| ID | Summary |"
    echo "|---|---|"
  } >> "$OUT"

  while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    # line looks like: - **PREFIX-NNN** — summary text
    rule_id="$(echo "$line" | grep -oE '[A-Z]{2,7}-[0-9]{3,}' | head -n1)"
    summary="$(echo "$line" | sed -E 's/^- \*\*[A-Z]{2,7}-[0-9]{3,}\*\* —? *//')"
    # Escape pipe characters in summary for table.
    summary_escaped="${summary//|/\\|}"

    prefix="${rule_id%%-*}"
    topic="$(echo "$prefix" | tr '[:upper:]' '[:lower:]')"
    ref_path="skills/${skill_name}/references/${topic}.md"
    anchor="$(echo "$rule_id" | tr '[:upper:]' '[:lower:]')"

    if [[ -f "${PLUGIN_ROOT}/${ref_path}" ]]; then
      link="[\`${rule_id}\`](${ref_path}#${anchor})"
    else
      # No matching reference file — search references/ for the anchor.
      found=""
      for ref in "${skill_dir}references/"*.md; do
        [[ -f "$ref" ]] || continue
        if grep -q "^## ${rule_id} " "$ref"; then
          rel="$(realpath --relative-to="$PLUGIN_ROOT" "$ref")"
          link="[\`${rule_id}\`](${rel}#${anchor})"
          found="yes"
          break
        fi
      done
      [[ -z "$found" ]] && link="\`${rule_id}\`"
    fi

    echo "| ${link} | ${summary_escaped} |" >> "$OUT"
  done <<< "$rule_lines"

  echo >> "$OUT"
done

echo "wrote: $OUT"
